require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

# task :default => :search1

# desc "run cucumber Hkgta test case under projects folder."
# Cucumber::Rake::Task.new(:Hkgta) do |t|
#   t.cucumber_opts = "projects/Hkgta/features --format pretty"
# end

namespace :test do
  Cucumber::Rake::Task.new(:start) do |task|
    #options are set using environment instead
  end
  def create_options(project_name, extra_opts = 'BROWSER="CHROME" DEBUG="OFF"')
    Dir::mkdir('results') if not File.directory?('results')
    opts = []
    opts += ["project/#{project_name}"]
    opts += ["--require", "project/#{project_name}/features"]
    opts += ["--format pretty"]
    opts += ["--format html --out results/reports.html --format json --out report.json -f json -out cucumber.json"]
    opts += [extra_opts]
    return opts.join(" ")
  end
  def create_options_with_tags(project_name, tags, extra_opts = 'BROWSER="CHROME" DEBUG="OFF"')
    Dir::mkdir('results') if not File.directory?('results')
    opts = []
    opts += ["project/#{project_name}"]
    opts += ["--require", "project/#{project_name}/features"]
    opts += ["--tag #{tags}"]
    opts += ["--format pretty"]
    opts += ["--format html --out results/reports.html --format json --out report.json-f json -out cucumber.json"]
    opts += [extra_opts]
    return opts.join(" ")
  end
  desc "run cucumber search1 test cases under projects folder.
Usage:
      bundle exec rake test:search1"
  task :search1 do
    ENV['CUCUMBER_OPTS'] = create_options "search1"
    Rake::Task['test:start'].invoke()
  end
  desc "Run specified test in a given project folder
Usage:
      bundle exec rake test:project[search1,'BROWSER=chrome DEBUG=OFF']
Or
      bundle exec rake test:project[search1]"
  task :project, [:project_name, :extra_opts] do |t, args|
    ENV['CUCUMBER_OPTS'] = create_options args[:project_name], args[:extra_opts]
    Rake::Task['test:start'].invoke()
  end

  desc "Run specified test in a given project folder with cucumber profile
Usage:
      bundle exec rake test:project_with_profile[search1,google_search,'BROWSER=chrome DEBUG=OFF']
Or
      bundle exec rake test:project_with_profile[search1,google_search]"
  task :project_with_tags, [:project_name, :tags, :extra_opts] do |t, args|
    ENV['CUCUMBER_OPTS'] = create_options_with_tags args[:project_name], args[:tags], args[:extra_opts]
    Rake::Task['test:start'].invoke()
  end
end
